# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/usuario/Pr-ctica-Cadena-Simbolos-y-ALfabeto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/usuario/Pr-ctica-Cadena-Simbolos-y-ALfabeto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/usuario/Pr-ctica-Cadena-Simbolos-y-ALfabeto/CMakeFiles /home/usuario/Pr-ctica-Cadena-Simbolos-y-ALfabeto/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/usuario/Pr-ctica-Cadena-Simbolos-y-ALfabeto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CadenaMain

# Build rule for target.
CadenaMain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CadenaMain
.PHONY : CadenaMain

# fast build rule for target.
CadenaMain/fast:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/build
.PHONY : CadenaMain/fast

src/Alfabeto.o: src/Alfabeto.cc.o

.PHONY : src/Alfabeto.o

# target to build an object file
src/Alfabeto.cc.o:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/src/Alfabeto.cc.o
.PHONY : src/Alfabeto.cc.o

src/Alfabeto.i: src/Alfabeto.cc.i

.PHONY : src/Alfabeto.i

# target to preprocess a source file
src/Alfabeto.cc.i:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/src/Alfabeto.cc.i
.PHONY : src/Alfabeto.cc.i

src/Alfabeto.s: src/Alfabeto.cc.s

.PHONY : src/Alfabeto.s

# target to generate assembly for a file
src/Alfabeto.cc.s:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/src/Alfabeto.cc.s
.PHONY : src/Alfabeto.cc.s

src/Cadena.o: src/Cadena.cc.o

.PHONY : src/Cadena.o

# target to build an object file
src/Cadena.cc.o:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/src/Cadena.cc.o
.PHONY : src/Cadena.cc.o

src/Cadena.i: src/Cadena.cc.i

.PHONY : src/Cadena.i

# target to preprocess a source file
src/Cadena.cc.i:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/src/Cadena.cc.i
.PHONY : src/Cadena.cc.i

src/Cadena.s: src/Cadena.cc.s

.PHONY : src/Cadena.s

# target to generate assembly for a file
src/Cadena.cc.s:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/src/Cadena.cc.s
.PHONY : src/Cadena.cc.s

src/Symbol.o: src/Symbol.cc.o

.PHONY : src/Symbol.o

# target to build an object file
src/Symbol.cc.o:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/src/Symbol.cc.o
.PHONY : src/Symbol.cc.o

src/Symbol.i: src/Symbol.cc.i

.PHONY : src/Symbol.i

# target to preprocess a source file
src/Symbol.cc.i:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/src/Symbol.cc.i
.PHONY : src/Symbol.cc.i

src/Symbol.s: src/Symbol.cc.s

.PHONY : src/Symbol.s

# target to generate assembly for a file
src/Symbol.cc.s:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/src/Symbol.cc.s
.PHONY : src/Symbol.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/CadenaMain.dir/build.make CMakeFiles/CadenaMain.dir/src/main.cc.s
.PHONY : src/main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CadenaMain"
	@echo "... src/Alfabeto.o"
	@echo "... src/Alfabeto.i"
	@echo "... src/Alfabeto.s"
	@echo "... src/Cadena.o"
	@echo "... src/Cadena.i"
	@echo "... src/Cadena.s"
	@echo "... src/Symbol.o"
	@echo "... src/Symbol.i"
	@echo "... src/Symbol.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

